import React from "react";
import {
  EmptyState,
  Title,
  EmptyStateBody,
  EmptyStateVariant,
  EmptyStateIcon,
  Bullseye,
} from "@patternfly/react-core";
import { RocketIcon } from "@patternfly/react-icons";

export const Welcome: React.FC = () => {
  return (
    <Bullseye>
      <EmptyState variant={EmptyStateVariant.large}>
        <EmptyStateIcon icon={RocketIcon} />
        <Title headingLevel="h4" size="lg">
          Welcome to Windup
        </Title>
        <EmptyStateBody>
          Windup helps you to visualize the report generated by Migration
          Toolkit for Applications while analysing your Java application.
        </EmptyStateBody>
      </EmptyState>
    </Bullseye>
  );
};
